version: '3.8'
services:
  mysql:
    image: library/mysql:8.0
    restart: always
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: leboncode
    volumes:
      - sf7:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

    ports:
      - 8080:80
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sf-api-php
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
volumes:
  sf7:
